### ISSUE TITLE
Multiple document equivalences

### ISSUE THREAD

**Issue by Treora** [openannotation/annotator-store#110]
While fixing https://github.com/hypothesis/h/issues/1777 I found that it could be a problem that only one document is returned when looking for equivalent documents; it may happen that there are several documents in the database that later on will turn out to become equals. I'm not sure what the exact behaviour is or should be, but it may be something to scrutinise at some moment.

Code in question:
https://github.com/openannotation/annotator-store/blob/d44c7c028bff9625808e43fabd3487dc6661533a/annotator/document.py#L37
https://github.com/openannotation/annotator-store/blob/d44c7c028bff9625808e43fabd3487dc6661533a/annotator/annotation.py#L60

**Comment by gergely-ujvari** [comment]
Fixed by https://github.com/openannotation/annotator-store/pull/112
