### ISSUE TITLE
Document plugin removing links without type

### ISSUE THREAD

**Issue by gergely-ujvari** [openannotation/annotator-store#116]
Folks, this is about a change I've introduced [here](https://github.com/openannotation/annotator-store/blob/master/annotator/document.py#L114)

I've introduced this function to sweep out incomplete links (who either have no type or no href)
Unfortunately, I've forgotten, that we in Hypothes.is fill the document's field with links which has no `type`

So, we this is an example of what we're saving:
```
            "link": [
            {
                "href": "http://www.forbes.com/sites/realspin/2014/03/31/the-ipccs-latest-report-deliberately-excludes-and-misrepresents-important-climate-science/print/"
            },
            {
                "href": "http://onforb.es/1ffC1p9",
                "type": "",
                "rel": "shortlink"
            }
            ]
```

And because the first one does not have a link type, we drop that.
My question is, should we keep them, or should we modify our document filling mechanism at H to provide a type for those links?

**Comment by tilgovi** [comment]
Where do we do this and why?

**Comment by gergely-ujvari** [comment]
Actually the annotator document plugin does it, that we use.
https://github.com/openannotation/annotator/blob/v1.2.x/src/plugin/document.coffee#L101

It creates a link without a type for the current document.location.href.

I think I should allow links without type then.
@nickstenning: Your thoughts on this?

**Comment by tilgovi** [comment]
We currently store that information also in the annotation's uri field so I'm not concerned about dropping it. I'd rather spend time on crafting a different approach to document metadata.
