### ISSUE TITLE
How to make annotator store working for DB2

### ISSUE THREAD

**Issue by khayati114** [openannotation/annotator-store#124]
Hi 
I am new to annotator and I find it pretty much doing all the chores I require to annotate a webpage.
I have a webapplication in spring calling rest resources on server .A part of this webapplication needs to have annotation on html files being opened in webclient. I am looking forward to use Annotator for this. 

Currently I just have downloaded the required plugins to make annotator work on my html files.It working great.Now I require below customizations  - 

1) To be able to open my customisable dialog to input the comments.
2) To be able to store annotations in my repository i.e DB2 database rather than annotateIt.

Kindly help me with these issues.How to proceed with storing of annotation in my preferref repository?Do i need to setup storePLugin ?If yes How to customise same to store in my own repository?

Thanks and Regards
Khayati

**Comment by tilgovi** [comment]
Please make sure you've read the documentation (http://annotator.readthedocs.org/en/v1.2.x/) and then follow up with any questions you might have on our mailing list (https://lists.okfn.org/mailman/listinfo/annotator-dev).

The sections about "Storage" and "Plugins" will be most useful. To implement your own storage you will need to expose an HTTP API in front of your database.

The "Tags" plugin is a good example of how you can add custom fields to the viewer and editor, but if you want more extensive customization it can be somewhat difficult.

The master branch is under development. The documentation is for the v1.2.x branch. If you get as far as needing to build your custom editor and you are really struggling to replace the built-in UI and events, the master branch makes it easier to do that.

**Comment by khayati114** [comment]
Hi 
Yes I Have gone through the documentation already and currently have been preparing the setup required to use storePlugin.I m completely new to python also.

As mentioned by you regarding building an HTTP api  in front of database , I can create a rest resource which will be responsible for creating,updating ,deleting annotation in database.But that would be in Java.What I see from storePlugin API's are rest calls are made from javascript or python ?? I am not sure would I achieve the same.

Secondly regarding comment editor I have my own custom comment editor which inputs the comment and also shows comments with reply hierarchy .I need to use this with annotator.Is that possible ? If yes then how ?

Thanks for your quick response.
Regards
Khayati

**Comment by tilgovi** [comment]
Please use the mailing list where others who don't follow the project as closely might help and participate. This issue tracker is for bug reports and concrete enhancement proposals. For support, the mailing list is the preferred channel.

**Comment by khayati114** [comment]
I have already send mail to the mentioned id " annotator-dev@lists.okfn.org. " but haven't got any response yet .

Regrading mailing list I have already raised subscription request twice to be able to participate and post my concerns but haven't got any confirmation so far 

Is there any alternate way to post my query at mailing list ?
