### ISSUE TITLE
Customise editor to show comment reply hierarchy 

### ISSUE THREAD

**Issue by khayati114** [openannotation/annotator-store#125]
Hi 

I wanna customize editor to show comment reply hierarchy something like its being done in hypothesis.How can I customize the same.If not can I invoke my own custom editor which will be doing this ?

I know this might not be a correct forum to ask about technical support but I have already raised several request to join the mailing list (https://lists.okfn.org/mailman/listinfo/annotator-dev) and also posted several queries on the comment id (annotator-dev@lists.okfn.org.) but none of them worked.

Please suggest how should I post my queries on the mailing list.I have also haven;t got any confirmation mail from this list.

Regards
Khayati

**Comment by nickstenning** [comment]
I don't understand the problem. You can subscribe to the list at https://lists.okfn.org/mailman/listinfo/annotator-dev, as you know. There is no approval process for joining the list.

Please join the list, send an email, and wait for replies. This is an open-source community and you may not get a response immediately. Please be patient.
