### ISSUE TITLE
Bulk store of annotations

### ISSUE THREAD

**Issue by htruong** [openannotation/annotator-store#128]
There are cases that the user might be getting the annotations from another source. For instance, the user might want to import the notes from other note-taking applications, which can range from several to hundreds of annotations at once. 

When that happens, current implementation of the atomic create function seems insufficient and inefficient. I have tried sending several hundreds of create requests and the annotator-store seemed to drop the requests every once in a while.

Should annotator-store adopt a bulk-create API?

I have made a patch here but I am not sure this is the direction you want to take.

**Comment by htruong** [comment]
https://github.com/htruong/annotator-store/commit/019365ab9d3df62d0ab9270aeec77d5bd7dce72f

**Comment by tilgovi** [comment]
I'm going to close for now. If you would like, submit your patch as PR and we can adapt it and merge after some discussion of API.
