### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by FRadice1977** [openannotation/annotator-store#129]
I have started the backend annotation store and it works with annotation share. Where can I view the posts? In what document does it post to?

**Comment by tilgovi** [comment]
If you're running the server with the default `run` script then the server runs on port 5000. You can go to "http://localhost:5000/search" and see all the annotations. For a description of all the routes, go to "http://localhost:5000/".

**Comment by FRadice1977** [comment]
Thank you for your reply. When I go to "http://localhost:5000/search" in the browser it says "rows" "total" 0. The front end works where by the posts are saving and remaining when I direct the posts to "http://localhost:5000/annotations/:id" . I think I'm nearly there but I seem to be missing something. Could I send you some screen shots via email?

**Comment by tilgovi** [comment]
Strange. You see the annotations get saved and then they are there when you refresh, but the server does not show them in search?

You can send screenshots if you like. You can post them here or send to the email on my profile.

**Comment by FRadice1977** [comment]
Hello, 

Thank you for your patience. I have sent the screenshots, but I don't think it will help. Can I confirm that the correct path to feed the rest api is 'http://localhost:5000/annotations/:id' or 'http://localhost:5000/annotations/api'. The frontend and backend seem to be working fine it's just that I may not be inserting the correct path in the front end for annotations to be saved on the server.

**Comment by tilgovi** [comment]
That looks right. I responded to your email. I think the problem is that
you are testing on a file: URL.

**Comment by FRadice1977** [comment]
I have managed to get it working now. Thank you for you help. :)
