### ISSUE TITLE
Using a different address besides 127.0.0.1

### ISSUE THREAD

**Issue by bulltorious** [openannotation/annotator-store#131]
Hello,

I am still new to linux, so please bear with me.  I am running this on a VM with IP address 192.168.1.113.

When I use 127.0.0.1:9200 and 127.0.0.1:5000 from the local machine, everything works fine

When I try the public IP address from a network machine, 192.168.1.113:9200 returns the elasticsearch JSON, but when I try 192.168.1.113:5000 nothing is returned from the annotator-store-master.  I get connection refused.

I tried changing the IP address in run.py from host = os.environ.get('HOST', '127.0.0.1') to host = os.environ.get('HOST', '192.168.1.113'), but now it just crashes when run.

Please advise.

**Comment by tilgovi** [comment]
You can use the bind address configuration: `gunicorn -b0.0.0.0:5000`.
In your environment, "0.0.0.0" is easiest. Some system calls refer to this as "INADDR_ANY", meaning any address, and it will cause gunicorn to listen on all interfaces.
