### ISSUE TITLE
root GET response not matching docs

### ISSUE THREAD

**Issue by birdsarah** [openannotation/annotator-store#71]
Hi,

Was just looking at http://docs.annotatorjs.org/en/latest/storage.html#root

When I call `$ curl http://localhost:5000/` on my locally running annotator-store, I see a list of all the possible methods for annotator-store, not the store information as documented. 

Maybe I'm missing something, happy to help update the documentation.

**Comment by tilgovi** [comment]
I'm not sure we need to have this here anymore. The v2 over on Annotator doesn't have this issue.
